import { AlertTriangle } from 'lucide-react-native';
import React from 'react';
import { Text, View } from 'react-native';
import { NutritionPlan } from '../../hooks/types';
import { personalStyles } from '../../styles/tabs/personalStyles';

interface StatusSectionProps {
    nutritionPlan: NutritionPlan;
    getStatusColor: (status: string) => string;
    getStatusText: (status: string) => string;
}

export const StatusSection: React.FC<StatusSectionProps> = ({
    nutritionPlan,
    getStatusColor,
    getStatusText,
}) => {
    return (
        <View style={personalStyles.section}>
            <Text style={personalStyles.sectionTitle}></Text>
            <View style={personalStyles.card}>
                <View style={personalStyles.statusHeader}>
                    <View style={[
                        personalStyles.statusIndicator,
                        { backgroundColor: getStatusColor(nutritionPlan.status || 'waiting') }
                    ]} />
                    <Text style={personalStyles.statusTitle}>
                        Status: {getStatusText(nutritionPlan.status || 'waiting')}
                    </Text>
                </View>
                <Text style={personalStyles.generatedBy}>
                    Generated by: {nutritionPlan.dibuatOleh || 'NutriAdvior AI'}
                </Text>
                {nutritionPlan.divalidasiOleh && (
                    <Text style={personalStyles.validatedBy}>
                        Validated by: {nutritionPlan.divalidasiOleh}
                    </Text>
                )}
                {(nutritionPlan.status || 'waiting') === 'waiting' && (
                    <View style={personalStyles.waitingNotice}>
                        <AlertTriangle size={16} color="#F59E0B" />
                        <Text style={personalStyles.waitingText}>
                            Rencana nutrisi Anda perlu disetujui oleh ahli gizi terlebih dahulu!
                        </Text>
                    </View>
                )}
            </View>
        </View>
    );
};

export default StatusSection;
