import { AlertTriangle } from 'lucide-react-native';
import React from 'react';
import { Text, View } from 'react-native';
import { personalStyles } from './styles';
import { NutritionPlan } from './types';

interface StatusSectionProps {
    nutritionPlan: NutritionPlan;
    getStatusColor: (status: string) => string;
    getStatusText: (status: string) => string;
}

export const StatusSection: React.FC<StatusSectionProps> = ({
    nutritionPlan,
    getStatusColor,
    getStatusText,
}) => {
    return (
        <View style={personalStyles.section}>
            <Text style={personalStyles.sectionTitle}>Status Rencana</Text>
            <View style={personalStyles.card}>
                <View style={personalStyles.statusHeader}>
                    <View style={[
                        personalStyles.statusIndicator,
                        { backgroundColor: getStatusColor(nutritionPlan.status) }
                    ]} />
                    <Text style={personalStyles.statusTitle}>
                        Status: {getStatusText(nutritionPlan.status)}
                    </Text>
                </View>
                <Text style={personalStyles.generatedBy}>
                    Generated by: {nutritionPlan.generatedBy}
                </Text>
                {nutritionPlan.validatedBy && (
                    <Text style={personalStyles.validatedBy}>
                        Validated by: {nutritionPlan.validatedBy}
                    </Text>
                )}
                {nutritionPlan.status === 'waiting' && (
                    <View style={personalStyles.waitingNotice}>
                        <AlertTriangle size={16} color="#F59E0B" />
                        <Text style={personalStyles.waitingText}>
                            Rencana Anda perlu disetujui oleh ahli gizi terlebih dahulu
                        </Text>
                    </View>
                )}
            </View>
        </View>
    );
};
