import { StyleSheet } from 'react-native';

export const indexTabStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#111827',
    },
    timeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    currentTime: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
    },
    dateNavigation: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
    },
    dateButton: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
    },
    selectedDate: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        flex: 1,
        textAlign: 'center',
    },
    reminderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 20,
        paddingVertical: 12,
        backgroundColor: '#FEF3C7',
        marginHorizontal: 20,
        marginVertical: 8,
        borderRadius: 8,
    },
    reminderText: {
        fontSize: 14,
        color: '#92400E',
        flex: 1,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 16,
        marginTop: 8,
    },
    mealCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.1)',
        elevation: 2,
    },
    mealCardCompleted: {
        backgroundColor: '#F0FDF4',
        borderColor: '#10B981',
    },
    mealCardOptional: {
        borderStyle: 'dashed',
        borderColor: '#9CA3AF',
    },
    mealTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        flexWrap: 'wrap',
    },
    optionalBadge: {
        fontSize: 9,
        color: '#6B7280',
        backgroundColor: '#F3F4F6',
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 3,
        fontWeight: '500',
        flexShrink: 0,
    },
    statusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 4,
    },
    statusIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '500',
    },
    mealHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
    },
    mealInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        flex: 1,
        minWidth: 0, // Allows shrinking below content size
    },
    mealTextContainer: {
        flex: 1,
        minWidth: 0,
    },
    mealIcon: {
        fontSize: 24,
        flexShrink: 0,
    },
    mealType: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111827',
        flexShrink: 1,
    },
    mealTime: {
        fontSize: 14,
        color: '#6B7280',
    },
    mealDetails: {
        alignItems: 'flex-end',
        flexShrink: 0,
        maxWidth: '45%',
    },
    mealFood: {
        fontSize: 13,
        fontWeight: '500',
        color: '#374151',
        textAlign: 'right',
    },
    mealCalories: {
        fontSize: 12,
        color: '#6B7280',
    },
    completedText: {
        textDecorationLine: 'line-through',
        color: '#6B7280',
    },
    completedBadge: {
        backgroundColor: '#10B981',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        alignSelf: 'flex-start',
        marginTop: 8,
    },
    completedBadgeText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '600',
    },
    quickActions: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
        marginBottom: 32,
    },
    actionButton: {
        flex: 1,
        backgroundColor: '#10B981',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 12,
        gap: 8,
    },
    scanButton: {
        backgroundColor: '#3B82F6',
    },
    actionButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    modalContainer: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
    },
    closeButton: {
        fontSize: 16,
        color: '#10B981',
        fontWeight: '600',
    },
    modalContent: {
        flex: 1,
        padding: 20,
    },
    mealPlanCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        marginBottom: 24,
        alignItems: 'center',
    },
    mealPlanTime: {
        fontSize: 16,
        color: '#6B7280',
        marginBottom: 8,
    },
    mealPlanFood: {
        fontSize: 20,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 8,
        textAlign: 'center',
    },
    mealPlanCalories: {
        fontSize: 16,
        color: '#10B981',
        fontWeight: '500',
    },
    modalActions: {
        flexDirection: 'row',
        gap: 12,
    },
    modalActionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#10B981',
        gap: 8,
    },
    modalActionText: {
        color: '#10B981',
        fontSize: 16,
        fontWeight: '600',
    },
    recommendationSection: {
        marginBottom: 24,
    },
    recommendationTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 12,
    },
    recommendationText: {
        fontSize: 14,
        color: '#6B7280',
        lineHeight: 20,
        marginBottom: 16,
    },
    optionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 12,
    },
    foodOptions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    foodOptionCard: {
        backgroundColor: '#F3F4F6',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    foodOptionText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#374151',
    },
    // Meal Detail Modal Styles
    mealInfoCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        marginBottom: 16,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
    },
    mealDetailTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6B7280',
        marginTop: 12,
        marginBottom: 4,
    },
    mealDetailValue: {
        fontSize: 16,
        fontWeight: '500',
        color: '#111827',
    },
    mealDetailCalories: {
        fontSize: 20,
        fontWeight: '700',
        color: '#10B981',
    },
    recommendationCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        marginBottom: 16,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
    },
    recommendationDescription: {
        fontSize: 14,
        color: '#6B7280',
        lineHeight: 20,
    },
    foodChoicesCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        marginBottom: 16,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
    },
    foodChoicesList: {
        gap: 8,
    },
    foodChoiceItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#F9FAFB',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    foodChoiceText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#111827',
        flex: 1,
    },
    foodChoiceCalories: {
        fontSize: 14,
        fontWeight: '600',
        color: '#10B981',
    },
    fluidIntakeCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        marginBottom: 16,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
    },
    fluidIntakeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    fluidIntakeIcon: {
        fontSize: 20,
    },
    fluidIntakeText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#111827',
    },
    fluidIntakeSubtext: {
        fontSize: 14,
        color: '#6B7280',
    },
    actionButtonsContainer: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
        paddingHorizontal: 16,
    },
    modalScanButton: {
        flex: 1,
        backgroundColor: '#10B981',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 12,
        gap: 8,
    },
    modalScanButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    adjustButton: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#3B82F6',
        gap: 8,
    },
    adjustButtonText: {
        color: '#3B82F6',
        fontSize: 16,
        fontWeight: '600',
    },
    statusButtonsContainer: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    completedButton: {
        flex: 1,
        backgroundColor: '#10B981',
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
    },
    completedButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    skippedButton: {
        flex: 1,
        backgroundColor: '#EF4444',
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
    },
    skippedButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    modalBottomSpacing: {
        height: 20,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    generateButton: {
        backgroundColor: '#10B981',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
    },
    generateButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    // Enhanced UI styles for meal plan integration
    errorContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FEF2F2',
        borderColor: '#FECACA',
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        margin: 16,
    },
    errorText: {
        flex: 1,
        color: '#B91C1C',
        fontSize: 14,
    },
    errorCloseButton: {
        padding: 4,
    },
    errorCloseText: {
        color: '#B91C1C',
        fontSize: 18,
        fontWeight: 'bold',
    },
    loadingContainer: {
        alignItems: 'center',
        padding: 24,
        backgroundColor: '#FFFFFF',
        margin: 16,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 16,
        color: '#6B7280',
        textAlign: 'center',
    },
    refreshButton: {
        backgroundColor: '#6B7280',
    },
    // Meal Plan Info and Empty State styles
    mealPlanInfo: {
        backgroundColor: '#F0F9FF',
        borderColor: '#3B82F6',
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        margin: 16,
        marginTop: 0,
    },
    mealPlanInfoText: {
        color: '#1E40AF',
        fontSize: 14,
        fontWeight: '500',
        textAlign: 'center',
    },
    emptyState: {
        alignItems: 'center',
        padding: 32,
        marginTop: 32,
    },
    emptyStateTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 8,
        textAlign: 'center',
    },
    emptyStateText: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 20,
    },
});

export default indexTabStyles;
