import { StyleSheet } from 'react-native';

export const nutritionScannerStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#111827',
    },
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: '#F3F4F6',
        marginHorizontal: 20,
        marginVertical: 16,
        borderRadius: 12,
        padding: 4,
    },
    tab: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
    },
    activeTab: {
        backgroundColor: '#FFFFFF',
        boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.1)',
        elevation: 2,
    },
    tabText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#6B7280',
        textAlign: 'center',
    },
    activeTabText: {
        color: '#111827',
        fontWeight: '600',
    },
    scanContent: {
        flex: 1,
        paddingHorizontal: 20,
    },
    scanSection: {
        marginBottom: 24,
    },
    scanTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 8,
    },
    scanDescription: {
        fontSize: 14,
        color: '#6B7280',
        lineHeight: 20,
        marginBottom: 24,
    },
    scanArea: {
        marginBottom: 20,
    },
    cameraContainer: {
        height: 300,
        backgroundColor: '#F3F4F6',
        borderRadius: 16,
        position: 'relative',
        padding: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cameraPlaceholder: {
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
    },
    cameraText: {
        fontSize: 14,
        color: '#6B7280',
        marginTop: 12,
        textAlign: 'center',
    },
    scanButton: {
        position: 'absolute',
        bottom: 20,
        left: 20,
        right: 20,
        backgroundColor: '#10B981',
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
    },
    scanButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    resultsTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 16,
    },
    nutritionLabel: {
        width: '100%',
        height: 250,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#111827',
        padding: 16,
    },
    nutritionHeader: {
        alignItems: 'center',
        marginBottom: 8,
    },
    nutritionTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: '#111827',
    },
    servingSize: {
        fontSize: 10,
        color: '#111827',
    },
    caloriesSection: {
        borderTopWidth: 8,
        borderTopColor: '#111827',
        paddingTop: 4,
        marginBottom: 8,
    },
    caloriesRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
    },
    caloriesLabel: {
        fontSize: 16,
        fontWeight: '700',
        color: '#111827',
    },
    caloriesValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#111827',
    },
    nutritionDetails: {
        flex: 1,
    },
    dailyValueHeader: {
        borderTopWidth: 1,
        borderTopColor: '#111827',
        paddingTop: 4,
        alignItems: 'flex-end',
    },
    dailyValueText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#111827',
    },
    nutritionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    nutritionRowIndent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingLeft: 16,
    },
    nutritionBold: {
        fontSize: 10,
        fontWeight: '700',
        color: '#111827',
    },
    nutritionText: {
        fontSize: 10,
        color: '#111827',
    },
    doneButton: {
        position: 'absolute',
        bottom: 16,
        right: 16,
        backgroundColor: '#111827',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
        gap: 4,
    },
    doneButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    resultsContainer: {
        flex: 1,
        paddingHorizontal: 20,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        marginBottom: 16,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
    },
    cardContent: {
        gap: 12,
    },
    section: {
        gap: 4,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#111827',
    },
    sectionValue: {
        fontSize: 16,
        color: '#374151',
    },
    photoPlaceholder: {
        width: '100%',
        height: 128,
        backgroundColor: '#E5E7EB',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    compositionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    compositionText: {
        fontSize: 14,
        color: '#111827',
    },
    compositionAmount: {
        fontSize: 14,
        color: '#6B7280',
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 12,
    },
    nutrientRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    nutrientName: {
        fontSize: 14,
        color: '#111827',
    },
    nutrientValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#111827',
    },
    microSection: {
        marginBottom: 16,
    },
    microSectionTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 8,
    },
    microNutrientRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    microNutrientName: {
        fontSize: 14,
        color: '#111827',
    },
    microNutrientValue: {
        fontSize: 14,
        color: '#111827',
    },
    totalCaloriesRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    totalCaloriesLabel: {
        fontSize: 18,
        fontWeight: '600',
        color: '#111827',
    },
    totalCaloriesValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#EA580C',
    },
    gradeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    gradeLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
    },
    gradeBadge: {
        backgroundColor: '#10B981',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 20,
    },
    gradeText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    statusSection: {
        marginBottom: 12,
    },
    statusLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 4,
    },
    statusValue: {
        fontSize: 14,
        color: '#10B981',
        fontWeight: '600',
    },
    descriptionSection: {
        gap: 4,
    },
    descriptionLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
    },
    descriptionText: {
        fontSize: 14,
        color: '#6B7280',
        lineHeight: 20,
    },
    actionButtons: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    saveButton: {
        flex: 1,
        backgroundColor: '#059669',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 12,
        gap: 8,
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    cancelButton: {
        flex: 1,
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#D1D5DB',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 12,
    },
    cancelButtonText: {
        color: '#374151',
        fontSize: 16,
        fontWeight: '600',
    },
    bottomNavigation: {
        backgroundColor: '#FFFFFF',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    bottomButton: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 8,
    },
    bottomSpacing: {
        height: 20,
    },
    nutrientText: {
        fontSize: 14,
        color: '#111827',
        marginBottom: 8,
    },
    totalCaloriesText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#EA580C',
        marginBottom: 12,
    },
    gradeTextSimple: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 12,
    },
    statusText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#10B981',
        marginBottom: 12,
    },
    closeButton: {
        padding: 4,
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#6B7280',
        marginTop: 2,
    },
    resetButton: {
        backgroundColor: '#F3F4F6',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
    },
    resetButtonText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#374151',
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 8,
    },
    tipsContainer: {
        backgroundColor: '#F0FDF4',
        padding: 16,
        borderRadius: 12,
        marginBottom: 20,
        borderLeftWidth: 4,
        borderLeftColor: '#10B981',
    },
    tipsTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#065F46',
        marginBottom: 8,
    },
    tipsText: {
        fontSize: 13,
        color: '#047857',
        marginBottom: 4,
    },
    cameraFrame: {
        position: 'absolute',
        top: 20,
        left: 20,
        right: 20,
        bottom: 60,
        borderRadius: 12,
    },
    cornerTL: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: 20,
        height: 20,
        borderTopWidth: 3,
        borderLeftWidth: 3,
        borderColor: '#10B981',
        borderTopLeftRadius: 12,
    },
    cornerTR: {
        position: 'absolute',
        top: 0,
        right: 0,
        width: 20,
        height: 20,
        borderTopWidth: 3,
        borderRightWidth: 3,
        borderColor: '#10B981',
        borderTopRightRadius: 12,
    },
    cornerBL: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        width: 20,
        height: 20,
        borderBottomWidth: 3,
        borderLeftWidth: 3,
        borderColor: '#10B981',
        borderBottomLeftRadius: 12,
    },
    cornerBR: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        width: 20,
        height: 20,
        borderBottomWidth: 3,
        borderRightWidth: 3,
        borderColor: '#10B981',
        borderBottomRightRadius: 12,
    },
    scanningContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    scanningContent: {
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        padding: 32,
        borderRadius: 20,
        boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.15)',
        elevation: 8,
    },
    scanningAnimation: {
        marginBottom: 24,
    },
    scanningTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 8,
        textAlign: 'center',
    },
    scanningDescription: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 20,
    },
    progressBar: {
        width: 200,
        height: 4,
        backgroundColor: '#E5E7EB',
        borderRadius: 2,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#10B981',
        borderRadius: 2,
        width: '70%',
    },
    resultsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 20,
    },
    confidenceCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.05)',
        elevation: 2,
    },
    confidenceLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8,
    },
    confidenceBar: {
        height: 6,
        backgroundColor: '#E5E7EB',
        borderRadius: 3,
        marginBottom: 8,
        overflow: 'hidden',
    },
    confidenceBarFill: {
        height: '100%',
        backgroundColor: '#10B981',
        borderRadius: 3,
    },
    confidenceText: {
        fontSize: 12,
        color: '#10B981',
        fontWeight: '600',
        textAlign: 'right',
    },
    summaryCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        marginBottom: 20,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
    },
    summaryTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 16,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    summaryItem: {
        alignItems: 'center',
        flex: 1,
    },
    summaryLabel: {
        fontSize: 12,
        color: '#6B7280',
        marginBottom: 4,
    },
    summaryValue: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
    },
    gradeBadgeSmall: {
        backgroundColor: '#10B981',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    gradeTextSmall: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '700',
    },
    scanBottomSpacing: {
        height: 40,
    },
    // Image preview styles
    imagePreviewContainer: {
        marginBottom: 16,
        padding: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    imageWrapper: {
        position: 'relative',
        alignItems: 'center',
    },
    previewImage: {
        width: 200,
        height: 200,
        borderRadius: 12,
        backgroundColor: '#F3F4F6',
    },
    removeImageButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: '#EF4444',
        borderRadius: 16,
        width: 32,
        height: 32,
        justifyContent: 'center',
        alignItems: 'center',
    },
    removeImageText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    // Scanned image display styles
    scannedImageContainer: {
        marginTop: 12,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#F3F4F6',
    },
    scannedImage: {
        width: '100%',
        height: 200,
        backgroundColor: '#F3F4F6',
    },
    imageLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8,
        paddingHorizontal: 4,
    },
    photoPlaceholderText: {
        fontSize: 12,
        color: '#9CA3AF',
        marginTop: 4,
        textAlign: 'center',
    },
});
