import { StyleSheet } from 'react-native';

export const personalStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        fontSize: 16,
        color: '#6B7280',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#111827',
    },
    editButton: {
        padding: 8,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
    },
    section: {
        marginVertical: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 12,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
    },
    statusHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    statusIndicator: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginRight: 8,
    },
    statusTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
    },
    generatedBy: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 4,
    },
    validatedBy: {
        fontSize: 14,
        color: '#10B981',
        fontWeight: '500',
    },
    waitingNotice: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        padding: 12,
        backgroundColor: '#FEF3C7',
        borderRadius: 8,
        gap: 8,
    },
    waitingText: {
        fontSize: 14,
        color: '#92400E',
        flex: 1,
    },
    profileRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        gap: 12,
    },
    profileLabel: {
        fontSize: 14,
        color: '#374151',
        flex: 1,
        maxWidth: '55%',
    },
    profileValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#111827',
        flex: 1,
        textAlign: 'right',
        flexWrap: 'wrap',
    },
    profileValuePlaceholder: {
        fontSize: 14,
        fontWeight: '400',
        color: '#9CA3AF',
        flex: 1,
        textAlign: 'right',
        flexWrap: 'wrap',
        fontStyle: 'italic',
    },
    bmiRow: {
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    bmiLabel: {
        fontSize: 14,
        color: '#374151',
        marginBottom: 4,
    },
    bmiValue: {
        fontSize: 14,
        fontWeight: '600',
    },
    calorieCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 24,
        alignItems: 'center',
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
    },
    calorieValue: {
        fontSize: 48,
        fontWeight: '700',
        color: '#10B981',
    },
    calorieLabel: {
        fontSize: 16,
        color: '#6B7280',
    },
    macroGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        justifyContent: 'space-between',
    },
    macroCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 14,
        alignItems: 'center',
        minWidth: '47%',
        maxWidth: '48%',
        flex: 1,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
    },
    macroValue: {
        fontSize: 22,
        fontWeight: '700',
        color: '#3B82F6',
        marginBottom: 4,
    },
    macroLabel: {
        fontSize: 12,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 16,
        flexWrap: 'wrap',
    },
    microRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        gap: 8,
    },
    microLabel: {
        fontSize: 14,
        color: '#374151',
        flex: 1,
        flexWrap: 'wrap',
        maxWidth: '70%',
    },
    microValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#10B981',
        flexShrink: 0,
        textAlign: 'right',
    },
    limitRow: {
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    limitLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 4,
    },
    limitValue: {
        fontSize: 14,
        color: '#6B7280',
        lineHeight: 20,
    },
    hydrationCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 3,
        gap: 12,
        flexWrap: 'wrap',
    },
    hydrationItem: {
        alignItems: 'center',
    },
    hydrationValue: {
        fontSize: 28,
        fontWeight: '700',
        color: '#3B82F6',
    },
    hydrationLabel: {
        fontSize: 13,
        color: '#6B7280',
        textAlign: 'center',
    },
    hydrationOr: {
        fontSize: 14,
        color: '#9CA3AF',
        fontStyle: 'italic',
        minWidth: 30,
        textAlign: 'center',
    },
    notesText: {
        fontSize: 14,
        color: '#6B7280',
        lineHeight: 20,
        textAlign: 'justify',
    },
    actionContainer: {
        gap: 12,
        marginVertical: 24,
    },
    actionButton: {
        backgroundColor: '#10B981',
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
    },
    actionButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    bottomSpacing: {
        height: 20,
    },
});
